FROM node:23-alpine

ENV NODE_ENV=development

WORKDIR /tye

RUN --mount=type=bind,source=/frontend/package.json,target=package.json \
    --mount=type=bind,source=/frontend/package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci

EXPOSE 5173

CMD ["npm", "run", "dev"]
