FROM node:23-alpine

ENV NODE_ENV=development

WORKDIR /tye

RUN --mount=type=bind,source=/backend/package.json,target=package.json \
    --mount=type=bind,source=/backend/package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci

RUN  npm install -g nodemon

EXPOSE 3000

CMD ["npm", "run", "dev"]
